
server:
 port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/person_website?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
#???????????????????????????
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
      prefix: classpath:/templates/
#???sql???????
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

